### ISSUE TITLE
Make video

### ISSUE THREAD

**Issue by JasonThomasData** [JasonThomasData/DocLink#10]
I want to show people the functionality of this app, so we can begin collecting data.

**Comment by JasonThomasData** [comment]
The video will be screen captured and sent via email to SSI

**Comment by JasonThomasData** [comment]
Here is the script Luke and Jason talked about on Tuesday evening. 
Feel free to change this if it's no good too.

> I am a case work at SSI, I've had a call from Akmaal, who is trying to find a doctor nearby who will be sensitive to his needs.
> So, I got to the this app that's available on PC (widescreen), and he's in Green Valley, Sydney.
> I know he speaks Arabic.
> So I enter Green Valley into the site and hit search.
> The search menu tells me there's one doctor nearby, Dr Mariam Joseph, and the clinic is nearby.
> I read Akmaal the address and I text him the url to the site.
> The link takes him directly to the result I've found.
> Aakmal can translate the site into Arabic, or I could send him the page already translated.
> It's up to Aakmal to call or look at a map of how to get there. If Aakmal wants, I could call.
> 
> Another use case is Mishaal, who wants to find a doctor himself. Aakmal has shared the Arabic page on the app with Mishaal.
> Mishaal lives in Liverpool and has picked his children up from school. One has a fever.
> Mishaal visits the Arabic page from his phone, which Akmaal shared with him.
> The phone detects his location automatically.
> Mishaal is able to find the closest doctor who speaks Arabic/has a translator available.

**Comment by JasonThomasData** [comment]
Hi @equivalentideas, how's this going?
Have you started this yet?
No pressure, just wondering

I just remembered today some tips in voice training at SBS.
- Voice over video always sounds more boring than in real life. Accentuate the gaps between tones or it'll sound very dull.
- Voice needs to sound strong. Imagine you're in a pub and you're talking to someone about something interesting.
- Stand/sit up straight. The listener can hear posture.
- Angle the microphone so your voice does not "pop". Spoken word creates short bursts of air that can sound like you're tapping the mic.

**Comment by equivalentideas** [comment]
Thanks 🎤 Always good to remember this stuff.

Brisbane ended up being totally exhausting so haven't had a chance to pick this back up yet.

Still keen :)

**Comment by JasonThomasData** [comment]
Sorry if that sounded like a lecture. These things helped me do voice stuff at SBS.

**Comment by equivalentideas** [comment]
> Sorry if that sounded like a lecture. These things helped me do voice stuff at SBS.

Not at all :) I've done it. I simplified the script a bit to just have one story, I think it gets the use across. And also I put in the ask for the people watching to contribute doctors.

I'll upload to YouTube.

**Comment by JasonThomasData** [comment]
Hiya, did you upload that to YouTube?
If so I can give our SSI contact a call today and the data collection can begin!

**Comment by equivalentideas** [comment]
https://youtu.be/0neLOCN_u6I

**Comment by JasonThomasData** [comment]
Hey, that's awesome.
I can call our man today or tomorrow and email it to them.
There's a few others I've been trying to contact.
There's also that Mariam fellow.

I'll look at that PR this arvo too, I've been meaning to.

Great stuff,

**Comment by JasonThomasData** [comment]
Good news @equivalentideas they like the video. They're saying now that it would be good to have the live link to show staff so they can test it. I think testing should happen in person personally. Thoughts?

If it's needed I can ask for a day off next week and head over there. I'm sure that will be fine.
