### ISSUE TITLE
Make layout fit small screens better

### ISSUE THREAD

**Issue by equivalentideas** [JasonThomasData/DocLink#18]
Currently the search form doesn't fit a small screen very well:

![img_4643](https://cloud.githubusercontent.com/assets/1239550/15306403/ab31017a-1c0d-11e6-98d7-6b3ee7fe5f65.jpg)

Fit that so it's clearer and more usable.

**Comment by equivalentideas** [comment]
I've fixed that major bug with the form, I'll close this and we can make new issues for other adaptions:
![screen shot 2016-05-17 at 9 15 38 am](https://cloud.githubusercontent.com/assets/1239550/15306677/1faf8e84-1c10-11e6-8366-9dc6b60a1e0b.png)

**Comment by JasonThomasData** [comment]
Nice work :)
