### ISSUE TITLE
Fix style issue with Doctor surgery name

### ISSUE THREAD

**Issue by JasonThomasData** [JasonThomasData/DocLink#26]
Since I've split the address into address and doctor surgery name, the name is sitting weird on the app.
I think the header element where the Doctor name is defined must be inline-block for every child.
I haven't checked that, but here's what it looks like.

Simple matter of putting that on a new line

![issuepic](https://cloud.githubusercontent.com/assets/9067490/15453615/ffa4eac2-205f-11e6-80a6-ab967638b3ba.jpg)

**Comment by equivalentideas** [comment]
Next time I think you should make this kinda change as a PR. It means we
can clean up all these issues before merging into master.

**Comment by equivalentideas** [comment]
> I think the header element where the Doctor name is defined must be inline-block for every child.
> I haven't checked that, but here's what it looks like.

I think it's actually flexbox, evenly spacing the elements.

**Comment by JasonThomasData** [comment]
Cool, anyway the entire issue is that element is in the header, so I'll
just need to remove that.
No matter, I'll push some work to a new PR tonight for you to look at.
Have fun in Bris mate.
