### ISSUE TITLE
Add basic visual design

### ISSUE THREAD

**Issue by JasonThomasData** [JasonThomasData/DocLink#3]
Create some pages for the design of the site.
Later we can turn these into the Rails templates.

**Comment by JasonThomasData** [comment]
Basic styles and HTML

**Comment by equivalentideas** [comment]
We think the character of the site should be:
- clear and warm
- polite and friendly but to-the-point

**Comment by JasonThomasData** [comment]
I'm doing the HTML

**Comment by equivalentideas** [comment]
I've added [Bitters](http://bitters.bourbon.io/) for basic default styles to build from. It just sets up some organised stylesheet files which is handy.

Here's the commits:
- e48131b Install Bourbon mixin library, dependency for Bitters
- ecd3a45 run: bitters install and remove main.scss
- 57cd5d9 Make the base type size a bit bigger
- 9bbc7a3 Make the base animation speed snappier
- da05089 Add a little spacing to the frame

Now we can customise and overwrite these styles for our basic design.

Worth reading a little about Bitters here http://bitters.bourbon.io/ and https://github.com/thoughtbot/bitters

**Comment by equivalentideas** [comment]
The main elements that we currently need to design are:
- [x] a doctor item in a list of search results
- [x] a list of doctor items (search results)
- [x] a search form
- [x] a way to change language

Any others you can think of @JasonThomasData ?

We did this very messy sketch at the pub last night, but we should make a readable version of this to work from:

![img_4526](https://cloud.githubusercontent.com/assets/1239550/13797111/31973e6c-eb5f-11e5-925e-206e9851ce43.jpg)

**Comment by equivalentideas** [comment]
We've added this basic design, closing this.
